["Attack"]
print = false
back = true
color = "red"
count = 4


["Pike"]
print = true
type = "Attack"
time = "action"
image = "images/pike"
description = """
**Attack roll**: +7 (19/20 crit)

**Damage**: [g]1d10[g]+4 +2d6 (if surprise), reroll 1 or 2

**Properties**: reach (15ft), push, heavy, two hands, piercing

**Push**: If you hit a creature with this weapon, you can push the creature up to 10
feet straight away from yourself if it is large or smaller.
"""

["Halberd"]
print = true
type = "Attack"
time = "action"
image = "images/halberd"
fontsize = "5.4"
description = """
**Attack roll**: +7 (19/20 crit)

**Damage**: [g]1d10[g]+4 +2d6 (if surprise), reroll 1 or 2

**Damage on cleave**: 1d10 +2d6 (if surprise), reroll 1 or 2

**Properties**: reach (15ft), cleave, heavy, two hands, slashing

**Cleave**: If you hit a creature with a melee attack using this weapon, you can make an
attack roll with the weapon against a second creature within 5ft of the first creature 
that is also within your reach. On a hit, the second creature takes the weapon's damage, 
but don't add your ability modifier to damage, unless that modifier is negative. 
You can make this extra attack only once per turn.
"""

["Handaxes"]
print = true
type = "Attack"
time = "action and bonus action"
image = "images/handaxe2"
fontsize = "5"
description = """
**Attack roll**: +7 (19/20 crit)

**Damage**: [g]1d6[g] (savage only once) +4 (only on first attack) +2d6 (if surprise)

**Properties**: Range (6/18m), light, thrown, slashing

**Vex**: If you hit a creature with this weapon and deal damage to the creature, you have
advantage on your next attack roll against that creature before the end of your next turn.

**Light**: When you take the attack action on your turn and attack with a light weapon,
you can make one extra attack as a bonus action later on the same turn. That extra attack
must be made with a different light weapon, and you don't add your ability modifier to the
extra attack's damage, unless that modifier is negative.
"""

["Net"]
print = false
type = "Attack"
time = "action"
image = "images/net2"
description = """
Dexterity saving throw versus 12 or become restrained.

When you take the attack action on your turn, you can replace one of your attacks with a throw 
of the net at a creature within 15 feet of you. The target must succeed on a dexterity saving throw 
agasint a dc equal to 8 + your proficiency bonus + your dexterity modifier. The target succeeds 
automatically if it's huge or larger.

On a failed save, the target has the restrained condition until it escapes the net.
"""
footer = """
15 feet
"""

[Restrained]
print = false
token = true
title = "Restrained (Net)"
type = "Condition"
image = "images/restrained2"
fontsize = "5"
description = """
You are restrained by a net!

 - A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.
 - Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.
 - The creture has disadvantage on dexterity saving throws.

**To escape**, the target must use its action to make a **DC 10 strength (athletics) check**, escaping on a success.
A creature within 5ft of the target can use its action to attempt the same thing.

Destroying the net (ac 10; 5 hp; immunity to bludgeoning, poison and psychic damage) also frees the target, ending the effect.
"""

["Second Wind"]
print = false
type = "Ability"
time = "bonus"
image = "images/second-wind"
description = """
You have a limited well of physical and mental stamina that you can draw on. As a bonus action, you can use it to regain hit points equal to 1d10 + your fighter level.
 
You can use this feature twice. You regain one expended use when you finish a short rest, and you regain all expended uses when you finish a long rest.
"""
footer = """
You can use twice
Recover one on short rest
Recover all on long rest
"""

["Action Surge"]
print = false
type = "Ability"
image = "images/action-surge"
description = """
You can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action, except the Magic action.

Once you use this feature, you must finish a Short Rest or Long Rest before you can use it again. Starting at level 17, you can use it twice before a rest but only once on a turn.
"""
footer = """
You can use once
Recover on short or long rest
"""

["Tactical Mind"]
print = false
type = "Ability"
image = "images/tactical-mind2"
description = """
You have a mind for tactics and getting the upper hand on and off the battlefield. When you fail an ability check, you can expend a use of your Second Wind to push yourself toward success.

Rather than regaining Hit Points, you roll **1d10** and add the number rolled to the ability check, potentially turning it into a success.

If the check still fails, this use of Second Wind isn’t expended.
"""

["Pole strike"]
print = true
type = "Ability"
time = "bonus"
image = "images/pole-strike"
description = """
Immediately after you take the Attack Action and attack with a Weapon that has the Heavy and Reach properties, you can use a Bonus Action to make a Melee Attack with the opposite end of the Weapon. The weapon's damage die for this attack is a d4, and it deals Bludgeoning Damage.

**Attack roll**: +7 (19/20 crit)

**Damage**: [g]1d4[g]+4 (savage only if first hit) +2d6 (if surprise), reroll 1 or 2

**Properties**: reach (15ft), heavy, two hands, bludgeoning
"""

["Reactive Strike"]
print = false
type = "Ability"
time = "reaction"
image = "images/reactive-strike"
description = """
While you are holding a Weapon that has the Heavy and Reach properties, you can use your Reaction to make one Melee Attack against a creature that enters the Reach you have with that Weapon.
"""

# [extra-abilities]
# type = 'extra'
# title = 'Abilities of **Bugubi**'
# image = 'images/bugubi.png'

# [extra-abilities.bugbear]
# title = 'Bugbear'
# "Darkvision" = 'You can see in dim light within 60 feet of you as if it were bright light and in darkness as if it were dim light. You discern colors in that darkness as shades of gray.'
# "Fey ancestry" = 'You have advantage on saving throws you make to avoid or end the charmed condition on yourself.'
# "Long-limbed" = 'When you make a melee attack on your turn, your reach for it is 5ft greater than normal.'
# "Powerful build" = 'You count as one size larger when determining your carrying capacity and the weight you can push, drag or lift. Carry: 255 kgs (17 7,5 2), push,drag or lift: 510 kgs'
# "Sneaky" = 'You are proficient in the stealth skill. In addition, without squeezing, you can move through and stop in a space large enough for a small creature.'
# "Surprise attack" = "If you hit a creature with an attack roll, the creature takes an extra 2d6 damage if it hasn't taken a turn yet in the current combat."

# [extra-abilities.soldier]
# title = 'Soldier'
# "Savage attacker" = "You have trained to deal particularly damaging strikes. When you take the attack action and hit a target with a weapon as part of that action, you can roll the weapon's damage dice twice and use either roll against the targe. You can use this benefit only once per turn."

# [extra-abilities.fighter]
# title = 'Fighter'
# "Fighting Style: Great weapon fighting" = 'You have honed your martial prowess and gain a Fighting style feat of your choice. When you roll a 1 or 2 on damage die for an attack you make with a melee weapon that you arewielding with two hands, you can reroll the die, and you must use the new roll. The weapon must have the Two-Handed or versatile property to gain this benefit.'
# "Second Wind" = 'You have a limited well of physical and mental stamina that you can draw on. As a bonus action, you can use it to regain hit points equal to 1d10 + your fighter level. You can use this feature twice. You regain one expended use when you finish a short rest, and you regain all expended uses when you finish a long rest.'
# "Weapon mastery" = 'Your training with weapons allows you to use the mastery property of three kinds of simple or martial weapons of your choice. Whenever you finish a long rest, you can practice weapon drills and change one of those weapon choices. Weapons: Halberd, pike and hand axe'
# "Action Surge" = "You can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action, except the Magic action. Once you use this feature, you must finish a Short Rest or Long Rest before you can use it again. Starting at level 17, you can use it twice before a rest but only once on a turn."
# "Tactical Mind" = "You have a mind for tactics and getting the upper hand on and off the battlefield. When you fail an ability check, you can expend a use of your Second Wind to push yourself toward success. Rather than regaining Hit Points, you roll 1d10 and add the number rolled to the ability check, potentially turning it into a success. If the check still fails, this use of Second Wind isn’t expended."

# [extra-abilities.champion]
# title = 'Champion'
# "Improved Critical (Champion)" = "Your attack rolls with weapons and Unarmed Strikes can score a critical hit on a roll of 19 or 20."
# "Remarkable Athlete" = "Thanks to your athleticism, you have Advantage on Initiative rolls and Strength (Athletics) checks. In addition, when you make a running long jump, the distance you can cover increases by a number of feet equal to your Strength modifier."


[Bugubi]
sheet = true
image = "images/bugubi.png"
title = '**Bugubi**, bugbear fighter 5, champion, chaotic neutral'

[Bugubi.attributes]
STR = [18, +4, +7]
DEX = [14, +2, +2]
CON = [16, +3, +6]
INT = [8, -1, -1]
WIS = [10, 0, 0]
CHA = [8, -1, -1]

[Bugubi.skills]
skills = [7, 5, 2, 5, -1, -1, -1, -1, -1, 0, 0, 0, 3, 0, -1, 2, -1, -1]
profic = [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
names = [
    'Athletics (\faIcon{arrow-up})',
    'Acrobatics',
    'Sleight of hand',
    'Stealth',
    'Arcana',
    'History',
    'Investigation',
    'Nature',
    'Religion',
    'Animal Handling',
    'Insight',
    'Medicine',
    'Perception',
    'Survival',
    'Deception',
    'Intimidation',
    'Performance',
    'Persuasion',
]

[Bugubi.boxes]
INIT = '+2\tiny{\faIcon{arrow-up}}'
AC = 16
HP = 53
PROF = "+3"
"2nd Wind" = "3"
SPEED = ["9m", "30ft"]

[Bugubi.proficiencies]
'\faIcon{comment}Languages' = "Common, goblin, aquan"
'\faIcon{gavel}Armor and weapons' = "Simple and martial weapons, all armor, shields"


[Bugubi.attacks]
"Sneaky" = "+2d6 damage if not acted yet in combat"
"Great w" = "Reroll 1/2 on damage with 2h weapons"
"Savage" = "Roll weapon die 2x, pick one, 1x/turn"
"Champion" = "Critical on 19/20"
"Halbard" = "+7, 1d10+4 sls (reach, cleave)"
"Pike" = "+7, 1d10+4 prc (reach, push)"
"Handaxe" = "+7, 1d6+4/1d6 sls (light, thrown 6/18m)"
"Net" = "Dex save vs. 12, restrained, dc 10 str"


[inventory]
inventory = true
title = "Inventory of **Bugubi**"
image = "images/bugubi.png"

"Wearing/At hand" = """
Traveler's clothes
Halberd
Pike
Scale Mail
Net
4 Handaxes
Healer's kit
Anel das Sombras
"""

"Backpack" = """
Crowbar, Hammer, 10 Pitons, Tinderbox
Waterskin
50 feet of rope
4 extra nets
4 extra handaxes
Shortbow, 20 arrows, Quiver
Playing cards
Troféu de ouro completamente amassado
Bestaca
Chicote Derruba Tonto
"""

"Wishlist" = """
Breastplate (mesma CA, sem desvantagem)
Half plate (CA 15 + dex)
Splint (CA 17)
Plate (CA 18)
"""

[extra1]
print = false
include = "tex/extra.tex"

[extra2]
print = true
include = "tex/extra2.tex"

[inventory.consumables]
"Torches" = 10
"Rations" = 10
"Healer's kit usages" = 10
"Healing potion (2d4+2)" = 3
GP = 852
XP = 7385
