# Cartas Quimera Calma - 2022-09-17


["Guidance Mantra"]
type = "Mantra"
time = "action"
cost = "at-will"
image = "images/guidance"
components = "VS"
# fontsize = 5
description = """
Once before the mantra ends, the target can roll a d4 and add the number rolled to one ability
check of its choice. It can roll the die before or after making the ability check.
The effect then ends.
"""
footer = """60 feet
Concentration, up to 1m"""


["Friendliness Mantra"]
type = "Mantra"
time = "action"
cost = "at-will"
image = "images/friendliness-mantra"
components = "SM"
# fontsize = 5
description = """
For the duration, you have advantage on all Charisma checks directed at one creature of your choice
that isn’t hostile toward you.

When the mantra ends, the creature realizes that you used magic to
influence its mood and becomes hostile toward you. A creature prone to violence might attack you.
Another creature might seek retribution in other ways (at the DM’s discretion),
depending on the nature of your interaction with it."""
footer = """Concentration, up to 1m"""

["Mantra of Suggestion"]
type = "Mantra"
time = "action"
cost = "ki - 2"
image = "images/mantra-of-suggestion"
components = "VM"
fontsize = 4
description = """
You suggest a course of activity (limited to a sentence or two) and magically influence a
creature you can see within range that can hear and understand you. Creatures that can’t be
charmed are immune to this effect. The suggestion must be worded in such a manner as to make
the course of action sound reasonable. Asking the creature to stab itself, throw itself onto
a spear, immolate itself, or do some other obviously harmful act ends the effect.

The target must make a **Wisdom** saving throw. On a failed save, it purses the course of action
you described to the best of its ability. The suggested course of action can continue for the
entire duration. If the suggested activity can be completed in a shorter time, the mantra ends
when the subject finishes what it was asked to do.

You can also specify conditions that will trigger a special activity during the duration.
For example, you might suggest that a knight give her warhorse to the first beggar she meets.
If the condition isn’t met before the mantra expires, the activity isn’t preformed.

If you or any of your companions damage the target, the mantra ends.
"""
footer = """Concentration, up to 8h"""

["Mantra of Toughness"]
type = "Mantra"
time = "action"
cost = "ki - 2"
image = "images/toughness"
components = "VSM"
description = """
Your mantra bolsters your allies with toughness and resolve. Choose up to three creatures within range.
Each target’s hit point maximum and current hit points increase by 5 for the duration.
"""
footer = """
30 feet
8 hours
"""

["Improved Guidance"]
type = "Class ability"
time = "bonus"
cost = "spiritual ki"
components = "V"
image = "images/cards-guidance-"
description = """
You can guide others with your mantra. To do so, you use a bonus action on your turn
to choose one creature other than yourself within 60 feet of you who can hear you and
don't have this bonus.

Once within the next 10 minutes, the creature can add **1d6** to one ability check,
attack roll, or saving throw it makes. The creature can wait until after it rolls
the d20 before deciding to roll the bonus die, but must decide before the DM says
whether the roll succeeds or fails.
"""
footer = """
60 feet
10 minutes
"""

["Tale of the Renowned Duelist"]
token = true
type = "Spiritual Ancestor"
image = "images/tale-renowned-duelist"
description = """
You make a melee spell attack against the target. On a hit, the target takes force damage equal to **2d6+5**.
"""

["Tale of the Beloved Friends"]
token = true
type = "Spiritual Ancestor"
image = "images/tale-beloved-friends"
description = """
The target and another creature of its choice it can see within 5 feet of it gains temporary
hit points equal to **16d+5**
"""

["Tale of the Runaway"]
token = true
type = "Spiritual Ancestor"
image = "images/tale-runaway"
description = """
The target can immediately use its reaction to teleport up to 30 feet to an unoccupied space
it can see. When the target teleports, it can choose up to **5** creatures it can see within
30 feet to immediately use the same reaction.
"""

["Tale of the Traveler"]
token = true
type = "Spiritual Ancestor"
image = "images/tale-traveler"
description = """
The target gains **1d6+4** temporary hit points.

While it has these temporary hit points, the target’s walking **speed increases by 10 feet** and it gains
a **+1 bonus to its AC**.
"""

[token-mantra-of-bravery]
title = "Mantra of Bravery"
token = true
image = "images/token-mantra-bravery"
description = """
For 1 minute or until dismissed, you are **immune** to being **frightened** and gain
**5 temporary hit points** at the start of each of your turns.

When the effect ends, you lose any remaining temporary hit points from this mantra.
"""

["Explosive Mantra"]
type = "Mantra"
cost = "at-will"
time = "action"
components = "S"
image = "images/card-explosive-mantra"
description = """
You create a burst of thunderous sound, which can be heard 100 feet away. Each creature
other than you within 5 feet of you must make a **Constitution** saving throw. On a
failed save, the creature takes **2d6 thunder** damage.
"""
footer = """
Self (5 foot readius)
Instantaneous"""

["Disturbing Mantra"]
type = "Mantra,cost=at-will"
time = "action"
components = "V"
image = "images/card-disturbing-mantra"
description = """
You unleash a string of mantras in an old language with subtle enchantments
at a creature you can see within range. If the target can hear you, it must succeed 
on a **Wisdom** saving throw or take **2d4 psychic** damage and have 
**disadvantage on the next attack roll** it makes before the end of its next turn.
"""
footer = """
60 feet
Instantaneous"""

["Energy Bow"]
type = "Mantra"
cost = "at-will"
time = "action"
components = "VS"
image = "images/card-energy-bow"
description = """
Two beams of crackling energy streaks toward one or two creatures within range. Make a ranged
spell attack for each beam. On a hit, the target takes **1d10 force** damage.
"""
footer = """
120 feet
Instantaneous"""

["Energy Sword"]
type = "Mantra"
cost = "at-will"
time = "action"
components = "SM"
image = "images/card-energy-sword"
description = """
You brandish your weapon and make a melee attack with it against one creature within
5 feet of you.

On a hit, the target suffers the weapon attack’s normal effects plus **1d8** fire damage,
and you can cause blue fire to leap from the target to a different creature of your choice
that you can see within 5 feet of it. The second creature takes **1d8+5 fire** damage.
"""
footer = """
Self (5 foot readius)
Instantaneous"""

["Mantra at will"]
back = true
color = "green"
count = 4

[quimera]
sheet = true
image = "images/big-quimera-calma.xcf2.png"
title = '**\faIcon{jedi}Quimera Calma**, Shaozun monk 5, lawful neutral'

[quimera.attributes]
STR = [8, -1, -1]
DEX = [16, +3, +6]
CON = [14, +2, +2]
INT = [10, 0, 0]
WIS = [12, +1, +1]
CHA = [20, +5, +8]

[quimera.skills]
skills = [0, 6, 4, 4, 1, 1, 1, 1, 3, 2, 4, 2, 7, 2, 8, 8, 5, 11]
profic = [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1]
names = [
    'Athletics',
    'Acrobatics',
    'Sleight of hand',
    'Stealth (\faIcon{hotjar}adv)',
    'Arcana',
    'History',
    'Investigation',
    'Nature',
    'Religion',
    'Animal Handling',
    'Insight',
    'Medicine',
    'Perception',
    'Survival',
    'Deception',
    'Intimidation',
    'Performance',
    'Persuasion',
]

[quimera.boxes]
INIT = "+4"
AC = 15
HP = 30
PROF = "+3"
"H DICE" = "5d8"
SPEED = ["9m", "30ft"]
"SP ATT" = "+8"
"SP SAVE" = 16
KI = "5/3"
"SP KI" = 5

[quimera.proficiencies]
'\faIcon{comment}Languages' = "Common, elvish, primordial, shaozun."
'\faIcon{gavel}Armor and weapons' = "Light and medium armor, shields, simple and martial weapons."
'\faTools{}Tools' = "Thieves' tools (traps or locks)"

[quimera.attacks]
"Sword (1)" = "+8, 1d8+5 slashing"
"Sword (2)" = "+8, 1d10+5 slashing"
"Energy S (1)" = "+8, 1d8+5+1d8 fire, 1d8+5 fire (oth)"
"Energy S (2)" = "+8, 1d10+5+1d8 fire, 1d8+5 fire (oth)"
"Energy bow" = "+8 (x2), 1d0 force"
"Disturbing M" = "wis, 2d4 psychic, disadv. att"
"Explosive M" = "con, AOE 5ft, 2d6 thunder"
